### PR TITLE
fix(opencode): comprehensive compatibility fix for opencode 1.18.x

### PR DESCRIPTION
**Pull request by LeoNardo-LB**
## Summary

The opencode adapter generated by `evolver setup-hooks --platform=opencode` does not actually work on opencode 1.18.x. This PR fixes **5 independent layers of incompatibility** discovered through systematic debugging with breakpoint diagnostics.

## Environment

- OS: Windows Server 2022
- opencode: 1.18.4 (scoop)
- Runtime: **Bun** (embedded in opencode; `typeof Bun === 'object'`)
- evolver: 1.92.1 (npm)

### Layer 1: CJS-ESM export format
**Symptom**: `Plugin export is not a function` — plugin silently skipped.

opencode loads plugins via Bun `import()`, then `readV1Plugin()` checks `mod.default` for `{ id, server }`. The original `module.exports = { Evolver }; module.exports.default = Evolver` lacks a `server` field.

**Fix**: `const pluginModule = { id: "evolver", server: Evolver }; module.exports = pluginModule; module.exports.default = pluginModule;`

### Layer 2: session.created event timing
**Symptom**: `session.created` never reaches the plugin (0 out of 1718 events).

opencode creates the session **before** loading plugins, so the event fires before the listener is registered.

**Fix**: Memory injection moved to `chat.message` hook (triggers on first user message).

### Layer 3: event hook cannot return values
**Symptom**: Even if the event fires, memory never reaches the LLM.

opencode's `event` hook signature is `(input) => Promise<void>` — return values are discarded.

**Fix**: Use `chat.message` hook which can mutate `output.parts` (forwarded to LLM).

### Layer 4: Bun spawnSync unreliable with script files on Windows
**Symptom**: `spawnSync('node', ['session-start.js'])` returns `ETIMEDOUT`.

Diagnostic self-test inside the Bun process:
```
spawnSync('node', ['-e', 'code'])     OK     (inline code)
spawnSync('node', ['script.js'])      ETIMEDOUT  (script file)
```

**Fix**: Inline memory reader using shared modules (`_runtimePaths`, `_memoryFiltering`) from the hooks directory. No `spawnSync` needed for memory injection.

### Layer 5: process.execPath is opencode.exe
`process.execPath` = `opencode.exe`, not a JS runtime. Cannot execute scripts.

## Bugbot Findings (all addressed)

| # | Finding | Status |
|---|---------|--------|
| 1 | Premature memoryInjected latch | Fixed: set after successful injection |
| 2 | Unscoped inline memory | Fixed: require shared modules for workspace filtering |
| 3 | spawnSync timeout stall | Fixed: inline-first, spawnSync as fallback |
| 4 | DIAG logging | Retained for maintainer verification |
| 5 | Skipped side effects | Fixed: fire-and-forget spawnSync after inline |
| 6 | Zero score as N/A | Fixed: !== undefined check |
| 7 | Full graph parse | Fixed: tail-read 64KB |
| 8 | Duplicated helpers | Fixed: require from hooks dir |
| 9 | Unsafe parts shape | Verified via breakpoint diagnostics |
| 10 | Incomplete path search | Fixed: findMemoryGraph() |
| 11 | Failed outcomes marked [+] | Fixed: [+]/[-] based on status |
| 12 | Test assertions outdated | Fixed: updated |

## Local Verification

```
[Evolution Memory] Recent 3 outcomes (3 success, 0 failed):
[+] 2026-07-21 score=0.8 signals=[perf_bottleneck,...] ...
✅ Memory injected into output.parts (723 chars)
✅ Dedup works (second message: parts=1, no re-inject)
✅ Workspace filtering via filterRelevantOutcomes
```

## Related

- #603 — initial export fix (superseded)
- #604 — previous iteration with Bugbot review (superseded, closed)
- #531 — original opencode integration discussion

---

> [!NOTE]
> **Medium Risk**
> Changes how and when evolution context reaches the LLM and alters plugin export contract for opencode 1.18.x; inline memory reads could diverge from hook-script behavior if shared modules drift.
> 
> **Overview**
> **Makes the generated opencode plugin loadable on 1.18.x and actually inject evolution memory into the LLM**, instead of being skipped or running session-start hooks that never reach the model.
> 
> The generated `evolver.js` now exports `{ id: "evolver", server: Evolver }` (with `default` pointing at the same object) so opencode’s Bun `import()` / v1 plugin shape accepts it. **Verify** also treats `mod.server` as the loadable factory, not only `Evolver`.
> 
> **Memory injection moves from `session.created` / `event` to `chat.message`**, which can prepend text to `output.parts` on the first user message (with a one-shot `memoryInjected` guard). The `event` handler only handles `session.idle` → `evolver-session-end.js`.
> 
> **Adds an inline memory path** that `require`s hook helpers `_runtimePaths` and `_memoryFiltering`, tail-reads the JSONL graph (64KB), formats outcomes with `[+]`/`[-]` and proper score handling, and falls back to `spawnSync` session-start when inline returns nothing; when inline succeeds it still fires a short session-start hook for side effects. Hook timeouts are bumped (session end 10s, signal detect 5s). Temporary `.evolver-diag.log` markers are included for maintainer debugging.
> 
> Tests update default-export expectations and unmanaged-plugin fixtures to the new module shape.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 39210a58de77005b973abbbc2e6c09ababce1e55. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by LeoNardo-LB** [comment]
Closing. Core evolution loop broken on opencode (Bun spawnSync ETIMEDOUT on Windows + session.idle never fires). Only memory injection works. Cherry-pick Layer 1 (export format) if useful.
